import { SHOP_STEPS } from "./campaign";

// Compact object/result names for cards and map labels. The full task text
// remains in TASKS.name for descriptions and purchase details.
export const TASK_LABELS: Record<string, string> = {
  ...Object.fromEntries(SHOP_STEPS.map(task => [task.id, task.name])),
  "shop-s1-r01": "Пол лавки",
  "shop-s1-r02": "Стены лавки",
  "shop-s1-r03": "Дверь и окно",
  "shop-s1-r04": "Витрина у окна",
  "shop-s1-r05": "Товары у окна",
  "shop-s1-r06": "Основной стеллаж",
  "shop-s1-r07": "Основные товары",
  "shop-s1-r08": "Хлебная секция",
  "shop-s1-r09": "Кассовый прилавок",
  "shop-s1-r10": "Касса",
  "shop-s1-r11": "Упаковка заказов",
  "shop-s1-r12": "Стеллаж заказов",
  "shop-s1-r13": "Готовые заказы",
  "shop-s1-r14": "Освещение лавки",
  "warehouse-s1-t01": "Уборка мусора",
  "warehouse-s1-t02": "Разбор сарая",
  "warehouse-s1-t03": "Уборка зарослей",
  "warehouse-s1-t04": "Деревья и пни",
  "warehouse-s1-t05": "Ровная площадка",
  "warehouse-s1-t06": "Разметка склада",
  "warehouse-s1-t07": "Фундамент склада",
  "warehouse-s1-t08": "Стены и каркас",
  "warehouse-s1-t09": "Крыша склада",
  "warehouse-s1-t10": "Дверь и окна",
  "warehouse-s1-t11": "Пол и отделка",
  "warehouse-s1-t12": "Свет и вход",
  "warehouse-s1-t13": "Паллеты приёмки",
  "warehouse-s1-t14": "Первые стеллажи",
  "warehouse-s1-t15": "Секции товаров",
  "warehouse-s1-t16": "Ящики бакалеи",
  "warehouse-s1-t17": "Холодная приёмка",
  "warehouse-s1-t18": "Проверка поставок",
  "warehouse-s1-t19": "Ручная тележка",
  "warehouse-s1-t20": "Разметка разгрузки",
  "warehouse-s1-t21": "Первая поставка",
  "warehouse-s1-t22": "Шкаф инвентаря",
  "warehouse-s1-t23": "Возвратная тара",
  "warehouse-s1-t24": "Комплектование лавки",
  "warehouse-s1-t25": "Контрольная поставка",
  "warehouse-s1-t26": "Ежедневное снабжение",

  "shop-s2-t01": "Расчистка ниши",
  "shop-s2-t02": "Пол в нише",
  "shop-s2-t03": "Стена отдела",
  "shop-s2-t04": "Секционный стеллаж",
  "shop-s2-t05": "Нижние шкафы",
  "shop-s2-t06": "Стойка бакалеи",
  "shop-s2-t07": "Крупы и макароны",
  "shop-s2-t08": "Полка чая",
  "shop-s2-t09": "Чай и кофе",
  "shop-s2-t10": "Масло и мёд",
  "shop-s2-t11": "Дозатор пакетов",
  "shop-s2-t12": "Кассовый терминал",
  "shop-s2-t13": "Широкий прилавок",
  "shop-s2-t14": "Боковая выдача",
  "shop-s2-t15": "Ящик тары",
  "shop-s2-t16": "Место тележки",
  "shop-s2-t17": "Корзины покупателей",
  "shop-s2-t18": "Держатели ценников",
  "shop-s2-t19": "Оконная витрина",
  "shop-s2-t20": "Вход с набережной",

  "warehouse-s2-t01": "Холодная зона",
  "warehouse-s2-t02": "Теплоизоляция",
  "warehouse-s2-t03": "Холодильный модуль",
  "warehouse-s2-t04": "Холодные полки",
  "warehouse-s2-t05": "Термометр",
  "warehouse-s2-t06": "Молочная секция",
  "warehouse-s2-t07": "Стеллаж муки",
  "warehouse-s2-t08": "Запасы муки",
  "warehouse-s2-t09": "Контейнеры сахара",
  "warehouse-s2-t10": "Запасы сахара",
  "warehouse-s2-t11": "Фруктовый стеллаж",
  "warehouse-s2-t12": "Фруктовые ящики",
  "warehouse-s2-t13": "Полка тары",
  "warehouse-s2-t14": "Мойка тары",
  "warehouse-s2-t15": "Сушильная решётка",
  "warehouse-s2-t16": "Шкаф инструментов",
  "warehouse-s2-t17": "Навес разгрузки",
  "warehouse-s2-t18": "Экраны навеса",
  "warehouse-s2-t19": "Освещение разгрузки",
  "warehouse-s2-t20": "Указатель секций",

  "fruit-yard-s1-t01": "Уборка мусора",
  "fruit-yard-s1-t02": "Разбор руин",
  "fruit-yard-s1-t03": "Уборка зарослей",
  "fruit-yard-s1-t04": "Деревья и пни",
  "fruit-yard-s1-t05": "Ровная площадка",
  "fruit-yard-s1-t06": "Разметка павильона",
  "fruit-yard-s1-t07": "Фундамент",
  "fruit-yard-s1-t08": "Каркас павильона",
  "fruit-yard-s1-t09": "Крыша павильона",
  "fruit-yard-s1-t10": "Вход и проёмы",
  "fruit-yard-s1-t11": "Пол и отделка",
  "fruit-yard-s1-t12": "Свет и вход",
  "fruit-yard-s1-t13": "Фруктовая стойка",
  "fruit-yard-s1-t14": "Корзины выкладки",
  "fruit-yard-s1-t15": "Яблоки и груши",
  "fruit-yard-s1-t16": "Цитрусовый стеллаж",
  "fruit-yard-s1-t17": "Секция бананов",
  "fruit-yard-s1-t18": "Стол упаковки",
  "fruit-yard-s1-t19": "Торговые весы",
  "fruit-yard-s1-t20": "Проход покупателей",
  "fruit-yard-s1-t21": "Фруктовый ассортимент",
  "fruit-yard-s1-t22": "Шкаф упаковки",
  "fruit-yard-s1-t23": "Корзины покупателей",
  "fruit-yard-s1-t24": "Выдача наборов",
  "fruit-yard-s1-t25": "Общая выкладка",
  "fruit-yard-s1-t26": "Открытие павильона",

  "fruit-yard-s2-t01": "Площадка пристройки",
  "fruit-yard-s2-t02": "Цоколь пристройки",
  "fruit-yard-s2-t03": "Фундамент зала",
  "fruit-yard-s2-t04": "Каркас пристройки",
  "fruit-yard-s2-t05": "Наружные стены",
  "fruit-yard-s2-t06": "Окна большого зала",
  "fruit-yard-s2-t07": "Крыша пристройки",
  "fruit-yard-s2-t08": "Входная дверь",
  "fruit-yard-s2-t09": "Проход в лавку",
  "fruit-yard-s2-t10": "Пол нового зала",
  "fruit-yard-s2-t11": "Большой стеллаж",
  "fruit-yard-s2-t12": "Ярусные корзины",
  "fruit-yard-s2-t13": "Новые фрукты",
  "fruit-yard-s2-t14": "Ягодная витрина",
  "fruit-yard-s2-t15": "Свежие ягоды",
  "fruit-yard-s2-t16": "Кассовая стойка",
  "fruit-yard-s2-t17": "Боковая выдача",
  "fruit-yard-s2-t18": "Освещение зала",
  "fruit-yard-s2-t19": "Скамья под навесом",
  "fruit-yard-s2-t20": "Вывеска большой лавки",

  "bakery-s1-t01": "Уборка участка",
  "bakery-s1-t02": "Разбор старых конструкций",
  "bakery-s1-t03": "Уборка зарослей",
  "bakery-s1-t04": "Деревья и пни",
  "bakery-s1-t05": "Ровная площадка",
  "bakery-s1-t06": "Разметка пекарни",
  "bakery-s1-t07": "Фундамент пекарни",
  "bakery-s1-t08": "Стены и каркас",
  "bakery-s1-t09": "Крыша пекарни",
  "bakery-s1-t10": "Дверь и окна",
  "bakery-s1-t11": "Пол и отделка",
  "bakery-s1-t12": "Свет и вход",
  "bakery-s1-t13": "Хлебная печь",
  "bakery-s1-t14": "Стол замеса",
  "bakery-s1-t15": "Шкаф ингредиентов",
  "bakery-s1-t16": "Стойка противней",
  "bakery-s1-t17": "Расстойка теста",
  "bakery-s1-t18": "Мойка инвентаря",
  "bakery-s1-t19": "Хлебная витрина",
  "bakery-s1-t20": "Лотки выпечки",
  "bakery-s1-t21": "Свежая выпечка",
  "bakery-s1-t22": "Шкаф упаковки",
  "bakery-s1-t23": "Окно выдачи",
  "bakery-s1-t24": "Полка заказов",
  "bakery-s1-t25": "Первая поставка хлеба",
  "bakery-s1-t26": "Открытие пекарни",
};

export function taskLabel(id: string, nameFallback?: string): string {
  return Object.hasOwn(TASK_LABELS, id) ? TASK_LABELS[id] : nameFallback?.trim() || "Работа";
}
